### ISSUE TITLE
Fix simple typo: retur -> return

### ISSUE THREAD

**Issue by timgates42** [mindflayer/python-mocket#108]
There is a small typo in tests/main/test_httpretty.py.
Should read `return` rather than `retur`.

**Comment by mindflayer** [comment]
Hi @timgates42, thanks for your contribution. I should clean that file though, since many tests have been commented out for features which `mocket` did not, and probably will never support.

**Comment by mindflayer** [comment]
I removed the unused tests from that file. Thanks for the hint, btw. I completely forgot I had to do it.
https://github.com/mindflayer/python-mocket/commit/3a76df216e1478187ca6451a6c9b23d9c1438f03
