### ISSUE TITLE
BlockingIOError() when mocking null-byte responses

### ISSUE THREAD

**Issue by amotl** [mindflayer/python-mocket#110]
Dear Giorgio,

first things first: Thanks for conceiving and maintaining this excellent pytest mocking module.

We just found MocketEntry instances pretending to respond with single null bytes like
```
MocketEntry(location=(None, None), responses=[0x00])
```
will not yield their responses properly due to the boolean-style test within [`MocketSocket.recv`](https://github.com/mindflayer/python-mocket/blob/3.8.4/mocket/mocket.py#L280-L281).

Instead, the `BlockingIOError()` will be raised.

With kind regards,
Andreas.

**Comment by mindflayer** [comment]
Hi @amotl,
I was trying to write a test which makes it fail that way, but I could not.
Could you please add a few lines of code which show the full picture?
Thank you very much in advance.

**Comment by amotl** [comment]
Dear Giorgio,

probably I didn't learn enough about Mocket yet / mixed up the data types. After tweaking the `responses` parameter to `[b'\x00']` to designate a single null-byte (see also [1]), everything worked smoothly.

So, let's just close this issue. Sorry for the noise and keep up the spirit!

With kind regards,
Andreas.

[1] https://github.com/hiveeyes/terkin-datalogger/blob/14a9bb5e4331733261083f3c90e0364ac9275b10/test/test_lorawan.py#L197-L198

**Comment by mindflayer** [comment]
I am aware it still lacks a proper documentation. I am trying to find the time to make it better.
Feel free to contact me in case you have other problems.
