### ISSUE TITLE
Can it mock socket errors?

### ISSUE THREAD

**Issue by dimaqq** [mindflayer/python-mocket#112]
It would be awesome if mocket could also mock all kinds of socket errors on demand.
I'd love to use this library for negative tests as well as regular tests...

**Comment by mindflayer** [comment]
I am studying a solution. I'll let you know soon if that can be done without breaking anything.

**Comment by mindflayer** [comment]
Hi @dimaqq, after months I spent some more time on it and I made it.

**Comment by mindflayer** [comment]
```python
    @mocketize
    def test_raise_exception(self):
        url = "http://github.com/fluidicon.png"
        Entry.single_register(Entry.GET, url, exception=IOError())
        with self.assertRaises(requests.exceptions.ConnectionError):
            requests.get(url)
```

**Comment by mindflayer** [comment]
Of course after a `pip install mocket==3.9.2`. :package: 
https://pypi.org/project/mocket/3.9.2/
