### ISSUE TITLE
MocketSocket support for context manager

### ISSUE THREAD

**Issue by fvigo** [mindflayer/python-mocket#139]
Hi,

MocketSocket doesn't seem to support context manager, so the construct:
```
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((target.host, target.port, 0, 0))
    s.sendall(something)
    data = s.recv(4096)
```

throws an AttributeError:
```
Traceback (most recent call last):
  File "/home/scanner/scanner.py", line 32, in scan
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
AttributeError: __enter__
```

Is it by design? Any way to work around it (besides rewriting the original code that uses `with socket.socket` )?

Thanks!

**Comment by mindflayer** [comment]
Hi @fvigo, it's simply the first time this use-case has ever been raised.
You could try to fix it, in case you want to try, or I'll have a look at it soon, potentially today afternoon or maybe during the week-end.

**Comment by fvigo** [comment]
Hey @mindflayer , I tried to fix it but probably you want to add a new UT for that scenario. The fix is based on the original implementation of `socket.socket`, plus adding a check for python >= 3.2 (as the context manager in socket as introduced then).

**Comment by mindflayer** [comment]
I've just pushed my branch with the feature, give me a minute and I'll publish a new version. :)

**Comment by mindflayer** [comment]
In your implementation you are closing the real `socket` in `__exit__`. Why this behaviour? Is there a specific user-case for it?

**Comment by fvigo** [comment]
It's based on this: https://hg.python.org/cpython/file/e57c8a90b2df/Lib/socket.py#l87

`__exit__()` gets called when you stop using an object in `with` scenarios, so it it was a real socket it would close it.

I assumed that if you are mocking a socket but you have an open truesocket behind it, you want to close it.

**Comment by mindflayer** [comment]
In this case I'd say it's not needed. Not sure if I am not considering a specific scenario that you have in mind.

**Comment by fvigo** [comment]
I don't think it's a big deal, but I won't understand where you close the true_socket if it's open (i.e. close the TCP connection). From what I see `MocketSocket.close()` doesn't really close it.

**Comment by mindflayer** [comment]
Actually you are right, now I picture it.

**Comment by mindflayer** [comment]
Here you are: https://pypi.org/project/mocket/3.9.39/

**Comment by fvigo** [comment]
Thanks a lot for the quick fix!
