### ISSUE TITLE
Some options not implemented in MocketSocket

### ISSUE THREAD

**Issue by fvigo** [mindflayer/python-mocket#142]
**Describe the bug**
When using mocked sockets in some conditions, certain socket properties are not properly implemented.

1. In AF_INET6 scenarios (IPv6 connection), `address` can be a tuple of four elements (see https://docs.python.org/3/library/socket.html#socket-families ), but the current implementation only takes tuples with 2 arguments. For example `socket.connect((host, port, 0, 0))` should not throw an error.
1. The socket type argument of `getaddrinfo()` is called `type` ( https://docs.python.org/3/library/socket.html#socket.getaddrinfo ) and not `socktype` as implemented here: https://github.com/mindflayer/python-mocket/blob/bce7cde62177bb23008ff57c84faaca1294b645d/mocket/mocket.py#L458

**Comment by fvigo** [comment]
Have you considered trying GitHub actions?

**Comment by mindflayer** [comment]
Yes, that would be the alternative.

**Comment by mindflayer** [comment]
Hi @fvigo, were you thinking to propose a PR related to this issue? Otherwise I'll have a look at it in the near future.

**Comment by fvigo** [comment]
Hi @mindflayer , sorry for the delayed response. I found a solution that allowed me to continue without requiring a change to `mocket`.

For IPV6 support, I think should be considered an enhancement, but the issues described here might create problems with the socket API. 

They should be both easy fixes: allow MocketSocket.connect() to support tuples of 4 elements, and  rename socktype to type in getaddrinfo. However, I'd recommend for you to take a look at those as, especially the latter, might maybe break some compatibility.
