### ISSUE TITLE
Mocket fails when there are Redis calls using `hiredis`

### ISSUE THREAD

**Issue by WisdomPill** [mindflayer/python-mocket#147]
**Describe the bug**
I have a `django` based software that makes http requests using `requests` and uses `django-redis` to store some data of what it has fetched. I have noticed that if the first network call in a `TestCase` is for `redis` then `mocket` mocks redis, otherwise it mocks only `requests`.

**To Reproduce**
```python
import requests
from django.core.cache import cache
from django.test.testcases import TestCase
from mocket import Mocket, mocketize
from mocket.mockhttp import Entry

class TestMocketStrangeBehaviour(TestCase):
    def tearDown(self):
        cache.clear()

    @mocketize
    def test_b_random_url(self):
        url = "http://www.example.com"
        Entry.single_register(Entry.GET, url)

        requests.get(url)

        self.assertTrue(Mocket.has_requests())

    @mocketize
    def test_a_random_url(self):
        url = "http://www.example.com"
        Entry.single_register(Entry.GET, url)

        cache.set("key", "value")

        requests.get(url)

        self.assertTrue(Mocket.has_requests())
```

will throw an exception
```
Error
Traceback (most recent call last):
  File "<decorator-gen-2>", line 2, in test_a_random_url
  File "/Users/anas/Projects/random_project/.venv/lib/python3.7/site-packages/mocket/mocket.py", line 627, in wrapper
    t(*args, **kw)
  File "/Users/anas/Projects/random_project/random_app/tests.py", line 34, in test_a_random_url
    cache.set("key", "value")
  File "/Users/anas/Projects/random_project/.venv/lib/python3.7/site-packages/django_redis/cache.py", line 27, in _decorator
    return method(self, *args, **kwargs)
  File "/Users/anas/Projects/random_project/.venv/lib/python3.7/site-packages/django_redis/cache.py", line 76, in set
    return self.client.set(*args, **kwargs)
  File "/Users/anas/Projects/random_project/.venv/lib/python3.7/site-packages/django_redis/client/default.py", line 156, in set
    return bool(client.set(nkey, nvalue, nx=nx, px=timeout, xx=xx))
  File "/Users/anas/Projects/random_project/.venv/lib/python3.7/site-packages/redis/client.py", line 1801, in set
    return self.execute_command('SET', *pieces)
  File "/Users/anas/Projects/random_project/.venv/lib/python3.7/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/Users/anas/Projects/random_project/.venv/lib/python3.7/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/Users/anas/Projects/random_project/.venv/lib/python3.7/site-packages/redis/connection.py", line 567, in connect
    self.on_connect()
  File "/Users/anas/Projects/random_project/.venv/lib/python3.7/site-packages/redis/connection.py", line 664, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/Users/anas/Projects/random_project/.venv/lib/python3.7/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/Users/anas/Projects/random_project/.venv/lib/python3.7/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/Users/anas/Projects/random_project/.venv/lib/python3.7/site-packages/redis/connection.py", line 427, in read_from_socket
    bufflen = recv_into(self._sock, self._buffer)
  File "/Users/anas/Projects/random_project/.venv/lib/python3.7/site-packages/redis/_compat.py", line 75, in recv_into
    return sock.recv_into(*args, **kwargs)
  File "/Users/anas/Projects/random_project/.venv/lib/python3.7/site-packages/mocket/mocket.py", line 264, in recv_into
    return buffer.write(self.read(buffersize))
AttributeError: 'bytearray' object has no attribute 'write'
```

If you swap names of the test functions it works as expected.

**Expected behavior**
Choose what to mock with some flag.

**Additional context**
It happens in macOS and ubuntu, with python3.7 and also 3.8

**Comment by mindflayer** [comment]
Hi @WisdomPill, I am having a look at that. Thanks for the feedback.
Before starting, I must say that usually when testing Django caching you use `DummyCache` (https://docs.djangoproject.com/en/3.1/topics/cache/#dummy-caching-for-development), but that of course has nothing to do with `mocket` failing, which has to be fixed. Maybe you could take it as a workaround for now.

**Comment by mindflayer** [comment]
The other thing is: I have to create a dummy project with Django, your script cannot work without it.

**Comment by WisdomPill** [comment]
Hello @mindflayer,
well, I can't use `DummyCache` because I am using some features of `django-redis` that are not standard in django cache, like a redis' `Lock`.
For now my look around is to run a dummy test that is a mere copy of `test_b_random_url ` of the example, so that alphabetically runs before.
I can create a dummy project with the test case in place if needed.

**Comment by mindflayer** [comment]
What version of `mocket` are you using?
Nothing is failing on my machine.
![Screenshot from 2021-03-20 20-09-27](https://user-images.githubusercontent.com/527325/111882874-3f110580-89b8-11eb-8cfd-487052686975.png)

**Comment by mindflayer** [comment]
`env DJANGO_SETTINGS_MODULE=app.app.settings pytest test.py`
Django's app has been created with a simple `django-admin startproject app`.

**Comment by mindflayer** [comment]
What `redis` version are you using?

**Comment by mindflayer** [comment]
All `mocket` tests are passing with the latest version of `redis`:
```
----------- coverage: platform linux, python 3.8.6-final-0 -----------
Name                                   Stmts   Miss  Cover   Missing
--------------------------------------------------------------------
mocket/__init__.py                         3      0   100%
mocket/async_mocket.py                    12      2    83%   7, 10
mocket/mocket.py                         392      7    98%   71-73, 87, 102, 189, 309
mocket/mockhttp.py                       124      0   100%
mocket/mockredis.py                       52      0   100%
mocket/plugins/__init__.py                 0      0   100%
mocket/plugins/httpretty/__init__.py      71      0   100%
mocket/plugins/httpretty/core.py           2      0   100%
mocket/plugins/pook_mock_engine.py        43      0   100%
mocket/utils.py                           20      0   100%
--------------------------------------------------------------------
TOTAL                                    719      9    99%

=========================================================================== 140 passed, 12 warnings in 9.71s ===========================================================================

(.venv) drizzt@mindflayer ~/r/python-mocket (master)> pip freeze | grep redis
redis==3.5.3
```

**Comment by WisdomPill** [comment]
I am using the same redis version.
I am trying to setup a dummy project.
Here is my pipfile with the dependencies needed if you want to try in the meantime.
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
django = "3.1.2"
django-redis = "==4.12.1"
mocket = "==3.9.40"
redis = "==3.5.3"
requests = "==2.24.0"
```

**Comment by mindflayer** [comment]
>  I am trying to setup a dummy project.

Thanks, that would help. :)

**Comment by WisdomPill** [comment]
With just the requirements of my previous comment is seems to work, but if I copy the requirements of the project in which there is the issue it happens again.
I stripped down the dependencies to see if the issue is still there and it is.
I left most of the dependencies that have to do with redis.
I will try to remove more dependencies, in the meantime [here is the link](https://github.com/WisdomPill/dummy_mocket) to the repo, you can have a look at the actions, I can add you to the repo if you want to use the action that is implemented there.
I can also add a matrix to see if with other versions of packages, python or redis it might differ, 
but at the moment I don't think so.

**Comment by WisdomPill** [comment]
It has to do with `hiredis`, I will read further probably tomorrow.
Thanks for the quick response.
I will let you know why it happens and if there is a quick fix to make `mocket` work in harmony with `hiredis`

**Comment by mindflayer** [comment]
> It has to do with `hiredis`, I will read further probably tomorrow.

That's quite strange, AFAIK `hiredis` has nothing to do with networking and it's for speeding up the Redis protocol parsing.

**Comment by mindflayer** [comment]
Let me know in case you feel I can be of help.

**Comment by WisdomPill** [comment]
I did some digging and removed django.
I found out that `redis-py` gives the error only when `hiredis` is available because it tries to use the socket to read (have a look [here](https://github.com/andymccurdy/redis-py/blob/1a41cfd95a53a95b078084d8627be6b6fba3bb71/redis/connection.py#L416)) the response. In fact now it gives the error back all the time regardless of the orther of the tests.
I never used mocket for redis so I do not know how it mocks behind the scenes, can you help me understand why even if using `@mocketized` I can access redis? I thought pocket will mock all the sockets, in fact that is the reason why the test fails.
I updated the project, maybe you can have a look at it?

**Comment by WisdomPill** [comment]
Okay, thanks for the explanation.
I already found some workaround in my projects, thanks for pointing out some solutions though.
I just like `mocket` and want to help by reporting this issue.

P.S. I wanted to make another point in why I am not using `DummyCache`, I prefer having the exact environment of staging and production during testing, so `DummyCache` is something that I never even thought of using to not incur in any preventable issue.

**Comment by mindflayer** [comment]
I understand your point of view and I believe it makes sense, especially if your logic can be different depending if something is cached or not, but also consider that a cache, by definition, should not be a "blocker". It's just there for optimizing the speed.
The first alternative I presented to you (context manager) implies you have a working Redis in your testing environment. If so, everything is working properly.

**Comment by mindflayer** [comment]
>  I just like mocket and want to help by reporting this issue.

Thank you so much for your help.
