### ISSUE TITLE
Mocket fails to mock HTTPS after upgrading `urllib3` to `1.26.5`

### ISSUE THREAD

**Issue by mmoraleda-smartprotection** [mindflayer/python-mocket#151]
**Describe the bug**
Mocket on version `3.9.41`  is not working well with HTTPS URLs.

**To Reproduce**
it's failing your test `tests/main/test_httpretty.py::test_rotating_responses_with_requests`.

```
FAILED tests/main/test_httpretty.py::test_rotating_responses_with_requests - requests.exceptions.SSLError: HTTPSConnectionPool(host='api.yahoo.com', port=443): Max retries exceeded with URL...
```

We have reproduced with these tests:
```
import requests,json
from unitest import TestCase

HTTPS_URL = "https://google.com"
HTTP_URL = "http://google.com"

class ReproduceSslError(Testcase):

    @mocketize
    def test_mocket_fine(self):
        Entry.single_register(
            Entry.GET,
            HTTP_URL,
            body=json.dumps({"foo":"bar"}),
            headers={"Content-Type": "application/json"}
        )
        response = requests.get(HTTP_URL)

    @mocketize
    def test_mocket_error(self):
        Entry.single_register(
            Entry.GET,
            HTTPS_URL,
            body=json.dumps({"foo":"bar"}),
            headers={"Content-Type": "application/json"}
        )
        response = requests.get(HTTPS_URL)
```
**Expected behavior**
It should mock HTTPS requests too.

**Docker image (please complete the following information):**
 - python:3.8-slim 

**Additional context**
- Python libs:
mocket = "==3.9.41"
requests = "==2.25.1"

**Comment by oschwald** [comment]
We are also [experiencing this](https://github.com/maxmind/minfraud-api-python/actions/runs/890529120). Our tests were working fine last week but stopped several days ago. The cause appears to be `urllib3` 1.26.5. If I downgrade to 1.26.4, the tests pass.

**Comment by mindflayer** [comment]
Thanks for the feedback. Something changed in the way `urllib3` deals with HTTPS, I need to spend some time on it.

**Comment by mindflayer** [comment]
This is what they claim they did:

```
1.26.5 (2021-05-26)

    Fixed deprecation warnings emitted in Python 3.10.
    Updated vendored six library to 1.16.0.
    Improved performance of URL parser when splitting the authority component.
```

This is the difference between the two versions:
https://github.com/urllib3/urllib3/compare/1.26.4...1.26.5

**Comment by mmoraleda-smartprotection** [comment]
My 2cents
As a partial solution, we have mocked `urllib3.connection.match_hostname` to silence this and it works.
This function consumes `SSLSocket.getpeercert` (override by MocketSocket?) around these functions should be the error.
```
@mock.patch("urllib3.connection.match_hostname", side_effect=None)
```

**Comment by mindflayer** [comment]
I bet this will help me to fix the issue.

**Comment by mindflayer** [comment]
It looks like it was not the only issue brought by the `urllib3` upgrade.

**Comment by mindflayer** [comment]
Here is a new version compatible with the current `urllib3`: https://pypi.org/project/mocket/3.9.42/

It has been hard but I managed to remove some code and make the rest simpler.
