### ISSUE TITLE
setup.py fails, missing requirements.txt file

### ISSUE THREAD

**Issue by c-w-m** [mindflayer/python-mocket#157]
**Describe the bug**
Missing `requirements.txt` file causing `setup.py` to fail.

**Comment by mindflayer** [comment]
What are you trying to do?

**Comment by c-w-m** [comment]
I would like to use mocket as the test environment for a SSL project.  As part of the development environment I'm loading mocket from tox via the command = `python -m pip install -e src/python-mocket`.  At this point it seems to work with my `requirements.txt` having only `decorator` as an entry.  This allows the `mocketoy` demo to run. Should there be more in `requirements.txt`?  - cheers

**Comment by c-w-m** [comment]
I'll close this, seems to be working well enough with:

================
File: requirements.txt
================

urllib3==1.26.7
decorator==5.1.0
http_parser==0.9.0
pook==1.0.2
python_magic==0.4.24
xxhash==2.0.2
xxhash_cffi==1.3.0

**Comment by mindflayer** [comment]
`pip install mocket` should work properly.

**Comment by mindflayer** [comment]
There is a `Makefile` which installs everything you need.
