### ISSUE TITLE
Strange behavior with multiple responses

### ISSUE THREAD

**Issue by ykharko** [mindflayer/python-mocket#158]
**Describe the bug**
I wanted to test specific logic of my application when retry logic is used. I wanted to emulate couple of fail responses and then successful one. I tried to use `Entry.register` method as it looks like its interface allows to pass multiple responses.
Almost everything works fine (difference responses are returned back) except for one thing: odd responses are missed.

**To Reproduce**
Probably the easiest way to reproduce it is not to use retries but just specify multiple responses with different status codes:
```python
from mocket import mocketize
from mocket.mockhttp import Entry, Response
import requests


TARGET_URL = 'http://merchant.store/webhook'


@mocketize
def main():
    Entry.register(
        Entry.POST,
        TARGET_URL,
        Response(body='{}', status=200),
        Response(body='{}', status=201),
        Response(body='{}', status=202)
    )

    response = requests.post(TARGET_URL, json={'test': 1})

    print(response.status_code)


if __name__ == '__main__':
    main()
```

**Expected behavior**
In the given example I expect 200 status code is returned back, but actually 201 status code is returned.

**Additional context**
OS: Ubuntu
Python version: 3.8.10
Requests version: 2.25.1
Mocket version: 3.10.0

**Comment by mindflayer** [comment]
Hi @ykharko,
this seems to be a very strange behaviour. I even noticed that changing the post to
```python
    response = requests.post(TARGET_URL, data="")
```
makes it behave normally.
I'll look into it ASAP.

**Comment by ykharko** [comment]
Thank you very much for quick reply. :)

**Comment by mindflayer** [comment]
Hi again, I am still on it, but I managed to isolate the issue and it's simpler than what I thought at first.
Here is a temporary solution for you:
```python
    # Entry.register(
    #     Entry.POST,
    #     TARGET_URL,
    #     Response(body='{"foo":"bar0"}', status=200),
    #     Response(body='{"foo":"bar1"}', status=201),
    #     Response(body='{"foo":"bar2"}', status=202)
    # )
    Entry.single_register(Entry.POST, TARGET_URL, body='{"foo":"bar0"}', status=200)
    Entry.single_register(Entry.POST, TARGET_URL, body='{"foo":"bar1"}', status=201)
    Entry.single_register(Entry.POST, TARGET_URL, body='{"foo":"bar2"}', status=202)
```

**Comment by mindflayer** [comment]
EDIT: I removed my previous comment because it was inaccurate. I am still working on it.

**Comment by mindflayer** [comment]
This was super-tricky, because in this case `requests` is calling `socket.sendall()` twice for each transaction. This was basically fooling `Mocket`. So, everything was working properly only when an empty body was sent or a GET method was used.
I am going to release a new version supporting this new use-case scenario.

**Comment by mindflayer** [comment]
Here it is: https://pypi.org/project/mocket/3.10.1/

Thanks again for opening the issue and making `mocket` a better tool for testing.

**Comment by ykharko** [comment]
Thank you very much for so quick fix!
