### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [mindflayer/python-mocket#178]
Could you please consider to use built in unittest.mock?

Background:
https://github.com/mindflayer/python-mocket
https://fedoraproject.org/wiki/Changes/DeprecatePythonMock

**Comment by mindflayer** [comment]
Here is a new version without `mock`: https://pypi.org/project/mocket/3.10.6/

**Comment by pgajdos** [comment]
Thanks!
