### ISSUE TITLE
Adding record/playback functionality?

### ISSUE THREAD

**Issue by bjmc** [mindflayer/python-mocket#2]
I'd like to be able to incorporate Mocket with a project like [vcrpy](https://github.com/kevin1024/vcrpy) ([see also](https://github.com/kevin1024/vcrpy/issues/8)) in order to be able to automatically save stored responses for use in tests.

Is this a feature that you'd like to see added to Mocket itself, or do you think I should just import and use Mocket as part of a separate wrapper library?

**Comment by mindflayer** [comment]
Just merged #43. I will write a blog-post in the next days presenting the last changes, with of course the recording feature.
