### ISSUE TITLE
Documentation..... is there any?

### ISSUE THREAD

**Issue by mrname** [mindflayer/python-mocket#20]
This looks super helpful, but I cannot find any docs or examples anywhere. Am I missing something?

**Comment by mindflayer** [comment]
Hi there, we already wrote many tests you can definitely use as examples.
Regards,
Giorgio

**Comment by bradwood** [comment]
It's a real shame there are no docs on this. Not even docstrings... And the tests aren't commented either... I've been trying with this lib for a while now, but, I think I'm going to have to give up...

**Comment by mindflayer** [comment]
@bradwood May I help you?

**Comment by mindflayer** [comment]
OK, since there is nothing productive here, I am going to close it again. Feel free to open an issue with a real problem, if possible after reading the `README` where you'll find some examples.
