### ISSUE TITLE
Documentation on direct socket mocking?

### ISSUE THREAD

**Issue by j3pic** [mindflayer/python-mocket#208]
I have a project that directly uses sockets, without HTTP. But all the documentation is geared towards HTTP. What can Mocket do when it comes to opening and closing connections (both via `connect` or `create_connection`, and via `listen` and `accept`), sending and receiving data, and using `select.epoll`? 

Also, are UDP sockets supported in any way? What about UNIX domain sockets, which can transfer not only bytes but also file descriptors?

**Comment by mindflayer** [comment]
Hi @j3pic, the only meaningful examples, like you said, are showing how to mock HTTP[S].
Many users ended up using Mocket for replacing HTTPretty, which is only capable of mocking web clients.
This said, Mocket implements also a stub for mocking Redis, which does not use HTTP as communication protocol. The biggest example of a non-web mock is probably that.
See https://github.com/mindflayer/python-mocket/blob/main/mocket/mockredis.py and you'll realise you need three main components:
- a main class Entry
- a Request class
- a Response class

**Comment by mindflayer** [comment]
Answering your first question, `create_connection` and `connect` are already mocked.

**Comment by mindflayer** [comment]
Hi @j3pic, did you manage to get started with low-level mocking of the `socket` module?

**Comment by mindflayer** [comment]
Feel free to open a new issue with a more specific question. Thanks!
