### ISSUE TITLE
Enable pook for newer Python versions

### ISSUE THREAD

**Issue by sarayourfriend** [mindflayer/python-mocket#210]
Pook now supports 3.11 as of v1.1.1, with CI up to 3.11 since v1.2.0.

Therefore, the check to exclude pook for version 3.11 can be removed:

https://github.com/mindflayer/python-mocket/blob/main/mocket/plugins/pook_mock_engine.py#L3

I'm shortly adding CI for 3.12 as well to ensure compatibility with the latest mocket version for Python 3.12.

**Comment by sarayourfriend** [comment]
@mindflayer I'll open a PR for this later in the week. The next version of pook (v1.2.2) will have tested support up to version 3.12.

**Comment by mindflayer** [comment]
I've already prepared a PR for fixing this, let me know when `pook` is ready for both 3.11 and 3.12.

**Comment by mindflayer** [comment]
Here is the new version which allows using `pook` plugin for Python versions newer than 3.10:
https://pypi.org/project/mocket/3.12.1/

**Comment by sarayourfriend** [comment]
Thanks!
