### ISSUE TITLE
missing socket.getblocking

### ISSUE THREAD

**Issue by kj4tmp** [mindflayer/python-mocket#227]
socket.getblocking appears to be missing.

Here is a minimally reproducible example:

```python
import socket

import mocket

my_mocket = mocket.mocket.MocketSocket(socket.AF_INET, socket.SOCK_STREAM)
my_mocket.connect(("locahost", 1234))
my_mocket.setblocking(False)

print(my_mocket.getblocking())  # expect False but get None here.
```

**Comment by mindflayer** [comment]
Hi @kj4tmp, thanks for opening this issue.
Here is a new version of Mocket with the missing method:
https://pypi.org/project/mocket/3.12.5/
