### ISSUE TITLE
Make python-magic an optional dependency?

### ISSUE THREAD

**Issue by satya-waylit** [mindflayer/python-mocket#254]
Looks like #82 removed a hard dependency on `python-magic`. Would it be appropriate to make it an optional dependency? This would allow installation on Windows. I'm happy to make a PR if so.

**Comment by mindflayer** [comment]
Hi @satya-waylit, I spent some time investigating alternatives and I found out there is a pure-Python implementation of `magic`. From now on Mocket will rely on it.

**Comment by mindflayer** [comment]
Here it is: https://pypi.org/project/mocket/3.13.1/
