### ISSUE TITLE
Properly handle requests that do multiple writes (e.g. by aiohttp 3)

### ISSUE THREAD

**Issue by sjaensch** [mindflayer/python-mocket#66]
The aiohttp client in version 3 does (at least) two writes if the request has a body: one for the headers, a second for the body. This was done in aio-libs/aiohttp#2126 and is documented in the "Are there changes in behavior for the user?" section of the description. Check out the [diff of the write_headers function](https://github.com/aio-libs/aiohttp/commit/bbf62184929f8f4ae36ad417005b5f9dad4d9e6a#diff-b01a901427ef6052963c0c1281a51872L241).

With mocket, this is not handled correctly. The body is lost. Would it be possible to implement proper handling of this scenario?

Example test failures: https://travis-ci.org/sjaensch/aiobravado/jobs/343058521

[Test 1 source](https://github.com/sjaensch/aiobravado/blob/master/tests/functional/request_func_test.py#L15)
[Test 2 source](https://github.com/sjaensch/aiobravado/blob/master/tests/functional/model_func_test.py#L177)

**Comment by mindflayer** [comment]
Thank you very much for the contribution. I'll have a look at that as soon as possible.

**Comment by mindflayer** [comment]
Hi @sjaensch, I did `pip install -U aiohttp` ending up with a virtualenv using version `aiohttp-3.0.2` and I was able to run all the `Mocket` tests. Also, if I look at the two failing tests in your code, I don't see you actually enabled `Mocket` as I do at this line:
https://github.com/mindflayer/python-mocket/blob/master/tests/tests35/test_http_aiohttp.py#L60

**Comment by sjaensch** [comment]
@mindflayer Mocket is enabled with this fixture: https://github.com/sjaensch/aiobravado/blob/dfacf2655053f765d832f50adff4659a79a3063d/tests/functional/conftest.py#L74

There are several other tests that use Mocket and continue to pass. Note that the two tests in question also pass if you use aiohttp<3.0. The fact that Mocket tests pass with aiohttp 3.0.2 tells me that this case is not covered by your tests. :)

All of your [aiohttp tests](https://github.com/mindflayer/python-mocket/blob/master/tests/tests35/test_http_aiohttp.py) do simple GET requests. Make sure you do a request that contains a body, so typically a POST request with some data. The aiobravado tests that do GET requests are still passing as well with aiohttp 3.0. As I explained in the description, aiohttp 3 does two network writes: One for the request headers, one for the request body. GET requests usually do not have a request body.

**Comment by mindflayer** [comment]
Hi @sjaensch, could you try to run your tests using this branch (https://github.com/mindflayer/python-mocket/tree/body-via-send)?

**Comment by sjaensch** [comment]
@mindflayer awesome! Both tests pass if I use that branch, well done!

**Comment by mindflayer** [comment]
Here you are: https://pypi.python.org/pypi/mocket/2.2.0

**Comment by mindflayer** [comment]
Here you are: https://pypi.python.org/pypi/mocket/2.2.0
