### ISSUE TITLE
md5 hashing is slow

### ISSUE THREAD

**Issue by thedrow** [mindflayer/python-mocket#80]
In https://github.com/mindflayer/python-mocket/blob/master/mocket/mocket.py#L265 we hash the response so we'll have a key. Using md5 to do so is slower than what can be done.
There are more modern hashing algorithms such as [xxhash](https://github.com/Cyan4973/xxHash).
Would you accept a PR that replaces MD5 with a non-cryptographic hash function?

**Comment by mindflayer** [comment]
Is it a real issue for your use-case? I am only concerned about introducing a breaking change, but I understand the value of it.

**Comment by mindflayer** [comment]
Also, whenever a user provides a JSON dump file, I would still look for the MD5 hash in case of a `KeyError`, to avoid CI pipelines already in place.

**Comment by mindflayer** [comment]
@thedrow still thinking about doing the change, right? No hurry, I am not pushing, just asking. :)

**Comment by thedrow** [comment]
Yeh.
I'll make the time for it.

**Comment by mindflayer** [comment]
https://pypi.org/project/mocket/2.6.0/

https://github.com/mindflayer/python-mocket/#speedups
