### ISSUE TITLE
Make magic dependency optional

### ISSUE THREAD

**Issue by tmbo** [mindflayer/python-mocket#81]
Installing the library using `pip install mocket` will lead to an exception if libmagic is not installed:

```
____________________ ERROR collecting tests/test_actions.py ____________________
ImportError while importing test module '/Users/tmbo/lastmile/bot-ai/rasa_core/tests/test_actions.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_actions.py:5: in <module>
    from mocket.mockhttp import Entry
../../../.virtualenvs/py3/lib/python3.6/site-packages/mocket/mockhttp.py:6: in <module>
    import magic
../../../.virtualenvs/py3/lib/python3.6/site-packages/magic.py:181: in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
E   ImportError: failed to find libmagic.  Check your installation
```

I checked the code, and although I see that it is nice to unburdon the user from specifying the response content type, but it is also kind of annoying to burdon everyone with installing libmagic. 

Can we make that dependency optional? (otherwise I can't add this as a dependency to https://github.com/RasaHQ/rasa_nlu)

**Comment by mindflayer** [comment]
Let me see what I can do. :+1:

**Comment by tmbo** [comment]
Looks good and should do the job :rocket:

**Comment by mindflayer** [comment]
I'll be releasing a new version with that change in a few hours.

**Comment by mindflayer** [comment]
Here is `mocket==2.5.0`: https://pypi.org/project/mocket/2.5.0/

**Comment by mindflayer** [comment]
Hi @tmbo, I am closing the issue, feel free to re-open it if you need additional support.
