### ISSUE TITLE
Query params should not need to be encoded in url

### ISSUE THREAD

**Issue by WisdomPill** [mindflayer/python-mocket#91]
First of all, thank you for your amazing job building this library.

I translated all my previous tests using httpretty to python rocket because the former seems to not be maintained as it supposed to.

The transition was very easy but I have to point out some small stuff, first of all there's no Mocket.has_request(), but this is minor and I understand you you would not include it.

But I found an issue with queryparams, they should not be in the url while registering the mock,
if you have a lot of params and you're using a library like requests to make requests, you don't know the order of the parameters in the url and this could be a pain in the ass to test with mocket. Is there a way to register only the path of the url without adding parameters? I would like just to check them later.

Thank you and again, I really appreciate your work and like the library.

**Comment by mindflayer** [comment]
If I understand your problem, `mocket` already provides a solution for that called `match_querystring`, have a look at:
https://github.com/mindflayer/python-mocket/blob/ed530d01a86f412814e908cf803db9f570877e00/mocket/mockhttp.py#L101

**Comment by WisdomPill** [comment]
That was fast.

Well, thank you, that's what I was looking for, maybe it's a good idea to put some documentation then.

Is there any docs? If you want I can definitely help with that

**Comment by mindflayer** [comment]
Well, the documentation is the weakest part of the whole project and I'd love to merge PRs related to that. :)

**Comment by mindflayer** [comment]
Let me know if it works for you, so I can close the issue.

**Comment by WisdomPill** [comment]
Yes, it works, thanks, I will definitely start on reading on how to use readthedocs for the documentation
